#############################################################################
# Makefile for building: testQT.app/Contents/MacOS/testQT
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  testqtbyme.pro
# Template: app
# Command: /Users/phanviethung/opt/anaconda3/bin/qmake -o Makefile testqtbyme.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/phanviethung/opt/anaconda3/include/qt -I/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets -I/Users/phanviethung/opt/anaconda3/include/qt/QtGui -I/Users/phanviethung/opt/anaconda3/include/qt/QtCore -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/phanviethung/opt/anaconda3/mkspecs/macx-clang
QMAKE         = /Users/phanviethung/opt/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/phanviethung/opt/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/phanviethung/opt/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testQT1.0.0
DISTDIR = /Users/phanviethung/Documents/Learn/UET/lab/testqtbyme/testqtbyme/.tmp/testQT1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/phanviethung/opt/anaconda3/lib
LIBS          = $(SUBLIBS) -L/Users/phanviethung/opt/anaconda3/lib -lQt5Widgets -framework DiskArbitration -framework IOKit -lQt5Gui -lQt5Core -framework OpenGL -framework AGL 
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qbtest.cpp \
		window.cpp moc_qbtest.cpp \
		moc_window.cpp
OBJECTS       = main.o \
		qbtest.o \
		window.o \
		moc_qbtest.o \
		moc_window.o
DIST          = /Users/phanviethung/opt/anaconda3/mkspecs/features/spec_pre.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/qdevice.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/device_config.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/unix.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/mac.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/macx.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/sanitize.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/gcc-base.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/clang.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/clang-mac.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/qconfig.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qt_functions.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qt_config.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/macx-clang/qmake.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/exclusive_builds.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/sdk.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/toolchain.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/toolchain.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/default_pre.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/default_pre.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/resolve_config.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/default_post.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/default_post.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/objective_c.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/warn_on.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qt.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/resources.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/moc.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/unix/opengl.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/uic.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/unix/thread.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qmake_use.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/file_copies.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/rez.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/testcase_targets.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/exceptions.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/yacc.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/lex.prf \
		testqtbyme.pro qbtest.h \
		window.h main.cpp \
		qbtest.cpp \
		window.cpp
QMAKE_TARGET  = testQT
DESTDIR       = 
TARGET        = testQT.app/Contents/MacOS/testQT

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d testQT.app/Contents/MacOS/ || mkdir -p testQT.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: testqtbyme.pro /Users/phanviethung/opt/anaconda3/mkspecs/macx-clang/qmake.conf /Users/phanviethung/opt/anaconda3/mkspecs/features/spec_pre.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/qdevice.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/device_config.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/unix.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/mac.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/macx.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/sanitize.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/gcc-base.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/clang.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/common/clang-mac.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/qconfig.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qt_functions.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qt_config.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/macx-clang/qmake.conf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/exclusive_builds.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/sdk.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/toolchain.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/toolchain.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/default_pre.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/default_pre.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/resolve_config.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/default_post.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/default_post.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/objective_c.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/warn_on.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qt.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/resources.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/moc.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/unix/opengl.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/uic.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/unix/thread.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/qmake_use.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/file_copies.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/rez.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/testcase_targets.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/exceptions.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/yacc.prf \
		/Users/phanviethung/opt/anaconda3/mkspecs/features/lex.prf \
		testqtbyme.pro \
		/Users/phanviethung/opt/anaconda3/lib/libQt5Widgets.prl \
		/Users/phanviethung/opt/anaconda3/lib/libQt5Gui.prl \
		/Users/phanviethung/opt/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile testqtbyme.pro
/Users/phanviethung/opt/anaconda3/mkspecs/features/spec_pre.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/qdevice.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/features/device_config.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/unix.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/mac.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/macx.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/sanitize.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/gcc-base.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/gcc-base-mac.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/clang.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/common/clang-mac.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/qconfig.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_charts.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_core.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designer.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gui.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_help.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_location.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_macextras.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_network.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qml.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quick.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_script.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sql.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_svg.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webview.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xml.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/phanviethung/opt/anaconda3/mkspecs/features/qt_functions.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/qt_config.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/macx-clang/qmake.conf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/phanviethung/opt/anaconda3/mkspecs/features/exclusive_builds.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/sdk.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/toolchain.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/toolchain.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/default_pre.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/default_pre.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/resolve_config.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/default_post.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/default_post.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/objective_c.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/warn_on.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/qt.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/resources.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/moc.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/unix/opengl.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/uic.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/unix/thread.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/qmake_use.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/file_copies.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/rez.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/mac/asset_catalogs.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/testcase_targets.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/exceptions.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/yacc.prf:
/Users/phanviethung/opt/anaconda3/mkspecs/features/lex.prf:
testqtbyme.pro:
/Users/phanviethung/opt/anaconda3/lib/libQt5Widgets.prl:
/Users/phanviethung/opt/anaconda3/lib/libQt5Gui.prl:
/Users/phanviethung/opt/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile testqtbyme.pro

qmake_all: FORCE

testQT.app/Contents/PkgInfo: 
	@test -d testQT.app/Contents || mkdir -p testQT.app/Contents
	@$(DEL_FILE) testQT.app/Contents/PkgInfo
	@echo "APPL????" > testQT.app/Contents/PkgInfo
testQT.app/Contents/Resources/empty.lproj: 
	@test -d testQT.app/Contents/Resources || mkdir -p testQT.app/Contents/Resources
	@touch testQT.app/Contents/Resources/empty.lproj
	
testQT.app/Contents/Info.plist: 
	@test -d testQT.app/Contents || mkdir -p testQT.app/Contents
	@$(DEL_FILE) testQT.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,macabo10.testQT,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,testQT,g" -e "s,@LIBRARY@,testQT,g" -e "s,@TYPEINFO@,????,g" /Users/phanviethung/opt/anaconda3/mkspecs/macx-clang/Info.plist.app >testQT.app/Contents/Info.plist

all: Makefile \
		testQT.app/Contents/PkgInfo \
		testQT.app/Contents/Resources/empty.lproj \
		testQT.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/phanviethung/opt/anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qbtest.h window.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp qbtest.cpp window.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r testQT.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/phanviethung/opt/anaconda3/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /Users/phanviethung/opt/anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_qbtest.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qbtest.cpp moc_window.cpp
moc_qbtest.cpp: /Users/phanviethung/opt/anaconda3/include/qt/QtCore/QObject \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnamespace.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlogging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qflags.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmutex.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnumeric.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstring.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qchar.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrefcount.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qarraydata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiterator.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpair.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qregexp.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmetatype.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		qbtest.h \
		moc_predefs.h \
		/Users/phanviethung/opt/anaconda3/bin/moc
	/Users/phanviethung/opt/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/phanviethung/opt/anaconda3/mkspecs/macx-clang -I/Users/phanviethung/Documents/Learn/UET/lab/testqtbyme/testqtbyme -I/Users/phanviethung/opt/anaconda3/include/qt -I/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets -I/Users/phanviethung/opt/anaconda3/include/qt/QtGui -I/Users/phanviethung/opt/anaconda3/include/qt/QtCore -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include qbtest.h -o moc_qbtest.cpp

moc_window.cpp: /Users/phanviethung/opt/anaconda3/include/qt/QtCore/QObject \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnamespace.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlogging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qflags.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmutex.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnumeric.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstring.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qchar.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrefcount.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qarraydata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiterator.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpair.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qregexp.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmetatype.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QWidget \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmargins.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrect.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsize.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpoint.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpalette.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qcolor.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qrgb.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qrgba64.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qbrush.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvector.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qmatrix.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpolygon.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qregion.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qdatastream.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiodevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qline.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtransform.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qimage.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpixmap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qshareddata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhash.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfont.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qcursor.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvariant.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qdebug.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtextstream.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlocale.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qset.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qurl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qurlquery.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qfile.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qvector2d.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		window.h \
		moc_predefs.h \
		/Users/phanviethung/opt/anaconda3/bin/moc
	/Users/phanviethung/opt/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/phanviethung/opt/anaconda3/mkspecs/macx-clang -I/Users/phanviethung/Documents/Learn/UET/lab/testqtbyme/testqtbyme -I/Users/phanviethung/opt/anaconda3/include/qt -I/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets -I/Users/phanviethung/opt/anaconda3/include/qt/QtGui -I/Users/phanviethung/opt/anaconda3/include/qt/QtCore -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include window.h -o moc_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QApplication \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qapplication.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlogging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qflags.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmutex.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnumeric.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstring.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qchar.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrefcount.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnamespace.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qarraydata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiterator.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpair.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qregexp.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmetatype.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qeventloop.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpoint.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsize.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qcursor.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmargins.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrect.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpalette.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qcolor.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qrgb.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qrgba64.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qbrush.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvector.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qmatrix.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpolygon.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qregion.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qdatastream.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiodevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qline.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtransform.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qimage.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpixmap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qshareddata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhash.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfont.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvariant.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qdebug.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtextstream.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlocale.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qset.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qurl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qurlquery.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qfile.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qvector2d.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qguiapplication.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qinputmethod.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QPushButton \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qicon.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QProgressBar \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qprogressbar.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qframe.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QSlider \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qslider.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qabstractslider.h \
		window.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/QObject \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qbtest.o: qbtest.cpp qbtest.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/QObject \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnamespace.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlogging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qflags.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmutex.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnumeric.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstring.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qchar.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrefcount.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qarraydata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiterator.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpair.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qregexp.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmetatype.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbtest.o qbtest.cpp

window.o: window.cpp window.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/QObject \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnamespace.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qconfig.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlogging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qflags.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmutex.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qnumeric.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstring.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qchar.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrefcount.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qarraydata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiterator.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpair.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringlist.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qregexp.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmetatype.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QWidget \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmargins.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qrect.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsize.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qpoint.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpalette.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qcolor.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qrgb.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qrgba64.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qbrush.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvector.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qmatrix.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpolygon.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qregion.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qdatastream.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qiodevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qline.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtransform.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qimage.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qpixmap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qshareddata.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qhash.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfont.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qcursor.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qevent.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qvariant.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qmap.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qdebug.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qtextstream.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qlocale.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qset.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qurl.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qurlquery.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qfile.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qvector2d.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QPushButton \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qicon.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/QApplication \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qapplication.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtCore/qeventloop.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qguiapplication.h \
		/Users/phanviethung/opt/anaconda3/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

moc_qbtest.o: moc_qbtest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qbtest.o moc_qbtest.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

